name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  go:
    uses: ./.github/workflows/go.yml
    secrets: inherit
  release:
    needs:
      - go
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            moefetch
          token: ${{ secrets.TOKEN_GITHUB }}
