name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: moefetch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            moefetch
          token: ${{ secrets.TOKEN_GITHUB }}
